### ISSUE TITLE
View label information

### ISSUE THREAD

**Issue by thartsel** [akulasainath/18frepo#5] opened 2015-06-19 15:33 UTC
As a patient, I want to view label information for drugs I am interested in so that I can access additional details

**Comment by ghost** [comment] 2015-06-19 19:47
**Acceptance Criteria**
-User clicks on drug name
-Label information is displayed for the drug name clicked

**Comment by ghost** [comment] 2015-06-24 14:47
Closed as duplicate of #17 .

**Closed as completed** 2015-06-24 14:47 UTC
Labels: duplicate
